### ISSUE TITLE
Failed to improve error

### ISSUE THREAD

**Issue by ParsaAminpour** [The-PR-Agent/pr-agent#289]
After three times to improve my code base, for the third time, the "failed to improve" error was raised
Currently, I use the Codium Vscode extension and I have no idea how to solve this problem!

**Comment by coditamar** [comment]
> After three times to improve my code base, for the third time, the "failed to improve" error was raised
> Currently, I use the Codium Vscode extension and I have no idea how to solve this problem!
> 

May I ask to share a screenshot?

Also, can you please share the Request ID?
You can find it by clicking on CodiumAI logo on the top-right of CodiumAI panel


Thank you for submitting this issue
