### ISSUE TITLE
[Question] Are there "insert here" tags for this?

### ISSUE THREAD

**Issue by dep** [The-PR-Agent/pr-agent#513]
I'd like to insert these things into my PR description, similar to `pr_agent:summary` (instead of adding a comment). Do template tags exist for these?

![image](https://github.com/Codium-ai/pr-agent/assets/55112925/f5bbc69e-c4df-4ba0-98fc-d4b13ce9886e)

**Comment by mrT23** [comment]
@dep 
No, it is not supported at the moment.
`/review` is a different tool (and a different call to LLM) than `/describe`, so the outputs of `/review` are not available as markers when editing the PR Description

**Comment by dep** [comment]
Ok thank you!
